server:
  port: 8082

spring:
  application:
    name: transactional-service
  config:
    import: optional:configserver:${CONFIG_SERVER_BASE_URL:http://localhost:8888}

  cloud:
    config:
      enabled: ${CONFIG_SERVER_ENABLED:false}
    discovery:
      enabled: ${DISCOVERY_ENABLED:false}

  datasource:
    url: ${TRANSACTION_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    dynamic: ${RABBITMQ_DYNAMIC}
    connection-timeout: 15000
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
    custom:
      transactional-events-exchange: transactional-exchange
      invoice-approved-queue: invoice-approved-queue
      payment-posted-queue: payment-posted-queue
      asset-transaction-created-queue: asset-transaction-created-queue
      bank-transaction-created-queue: bank-transaction-created-queue
      sales-invoice-created-queue: sales-invoice-created-queue
      receipt-created-queue: receipt-created-queue
      purchase-order-created-queue: purchase-order-created-queue
      vendor-created-queue: vendor-created-queue
      customer-created-queue: customer-created-queue
      fixed-asset-created-queue: fixed-asset-created-queue
      publish-transactional-events-job-cron: "*/30 * * * * *"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI}
          audiences: ${KEYCLOAK_AUDIENCES}

eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:false}

transactional:
  security:
    enabled: ${TRANSACTIONAL_SECURITY_ENABLED:false}

core-finance:
  enabled: ${CORE_FINANCE_ENABLED:false}
  url: ${CORE_FINANCE_URL:http://localhost:8081}

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL}
  realm: ${KEYCLOAK_REALM}
  client-id: ${TRANSACTION_CLIENT_ID}
  client-secret: ${TRANSACTION_CLIENT_SECRET}

api-gateway-base-url: ${API_GATEWAY_BASE_URL:http://localhost:8080}
