spring.application.name=payroll-service

spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

spring.datasource.url=jdbc:mysql://mysql-global:3306/payroll_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Admin@1234



spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

keycloak.server-url=http://localhost:9090/
keycloak.realm=payroll-realm
keycloak.client-id=payroll-service
keycloak.client-secret=Z6CcRV4pXdevgmnwarqc4gurRbdKAGNw

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# RabbitMQ Connection Stability
spring.rabbitmq.connection-timeout=15000
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.template.mandatory=true
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=1000
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.max-interval=10000

# RabbitMQ Exchanges
rabbitmq.exchange.loan=loan.exchange
rabbitmq.exchange.payroll=payroll.exchange

# RabbitMQ Routing Keys
rabbitmq.routing-key.loan.created=loan.created
rabbitmq.routing-key.loan.updated=loan.updated
rabbitmq.routing-key.loan.payment=loan.payment
rabbitmq.routing-key.payroll.created=payroll.created
rabbitmq.routing-key.payroll.processed=payroll.processed
rabbitmq.routing-key.payroll.approved=payroll.approved
rabbitmq.routing-key.payroll.cancelled=payroll.cancelled
rabbitmq.routing-key.salary.component=salary.component

# RabbitMQ Queues
rabbitmq.queue.payroll-created=payroll-created-queue
rabbitmq.queue.payroll-processed=payroll-processed-queue
rabbitmq.queue.payroll-approved=payroll-approved-queue
rabbitmq.queue.payroll-cancelled=payroll-cancelled-queue
rabbitmq.queue.loan-payment=loan-payment-queue
rabbitmq.queue.salary-component=salary-component-queue

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/payroll-realm

# $token = (Invoke-RestMethod `
#   -Uri "http://localhost:9090/realms/payroll-realm/protocol/openid-connect/token" `
#   -Method Post `
#   -Body @{
#       client_id     = "payroll-service"
#       client_secret = "Z6CcRV4pXdevgmnwarqc4gurRbdKAGNw"
#       grant_type    = "client_credentials"
#   } `
#   -ContentType "application/x-www-form-urlencoded").access_token
#
# $token | Set-Clipboard